### ISSUE TITLE
subctl verify should support overriding the nettest image path

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/subctl#313] opened 2022-10-20 15:48 UTC
**What would you like to be added**:
Currently, when `subctl verify ...` command is executed, it pulls the nettest image from `"quay.io/submariner/nettest:devel"`. It would be helpful to provide an option to override this image with some custom image.

**Comment by mkolesnik** [comment] 2022-11-07 08:56
> it pulls the nettest image from `"quay.io/submariner/nettest:devel"`.

Specifically it takes the image version based on the subctl compilation, so for branches it's based on branch name while for releases it'll use the release version.

With #316 merged, it should now take the nettest image based on the overrides, so it is possible to specify a custom image using the overrides flag when deploying Submariner.(or later by editing the CR).

We could, additionally, specify a flag to give a specific image URL which will take precedence over all other specifications. Is this the intent?

**Comment by nyechiel** [comment] 2023-03-19 10:01
@mkolesnik are you planning to fix this?

**Comment by maayanf24** [comment] 2023-03-30 08:58
I think this is duplicate of https://github.com/submariner-io/subctl/pull/526

**Comment by mkolesnik** [comment] 2023-04-02 14:33
As Maayan mentioned, this was solved by #526

**Closed as completed by mkolesnik** 2023-04-02 14:33 UTC
Labels: enhancement
