### ISSUE TITLE
Improve subctl unit tests

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/subctl#408] opened 2022-11-29 14:26 UTC
Now that we have SonarCloud to better see coverage, it's clear that subctl is the main gap. We currently ahve 4.6% coverage.

https://sonarcloud.io/component_measures?id=submariner-io_subctl&metric=new_coverage&view=list

Add unit tests to get coverage up, maybe targeting 70ish%. This can be split into smaller issues, maybe this should be treated as an epic.

**Comment by tpantelis** [comment] 2023-09-26 12:25
Duplicate of https://github.com/submariner-io/subctl/issues/422

**Closed as completed by tpantelis** 2023-09-26 12:25 UTC
Labels: enhancement, wontfix
